### Send metric
POST http://localhost:8080/update/
Content-Type: application/json

{
  "id": "superMetric",
  "type": "gauge",
  "value": 1234.345
}

### Get all metrics
GET http://localhost:8080/

### Get superMetric
GET http://localhost:8080/value/gauge/superMetric

### Get superMetric by post
POST http://localhost:8080/value/
Content-Type: application/json

{
  "id": "superMetric",
  "type": "gauge"
}
